version: "3"

services:
  app:
    container_name: express-mongo
    restart: always
    build:
     context: ./server
     dockerfile: Dockerfile.production
     args:
      - NODE_ENV=production
    ports:
      - "8088:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://api.spotify.coolify.ducphuclee.tech
      - CLIENT_ENDPOINT=https://spotify.coolify.ducphuclee.tech
      - SPOTIFY_PUBLIC=__your_spotify_client_id__
      - SPOTIFY_SECRET=__your_spotify_secret__
      - CORS=http://localhost:3000,http://localhost:3001,https://api.spotify.coolify.ducphuclee.tech,https://spotify.coolify.ducphuclee.tech
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify

  mongo:
    container_name: mongo
    image: mongo:4.4.8

  web:
    container_name: web
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.production
      args:
        - NODE_ENV=production
    ports:
      - "3340:3000"
    environment:
      - API_ENDPOINT=https://api.spotify.coolify.ducphuclee.tech