---
version: "3"
services:
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - CLI_ARGS= "-auth-mode=basic" #optional
    volumes:
      - ./config:/config
    ports:
      - 8282:8080 #DesktopGui
      - 8283:8081 #WebserverGui
    restart: unless-stopped


  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./web-config:/config
    ports:
      - 8284:8083
    restart: unless-stopped
    depends_on: 
      - calibre